---
application:
  name: "nicenuxsitev2"
  project: "oneofus"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "backend"
  version: "8.0"
routers:
- name: "main-nicenuxsitev2"
  routes:
  - application_name: "nicenuxsitev2"
    paths:
    - "/*"
